# Configuration for object detection node
/video_ros2_webserver:
  ros__parameters:
    # print debug output
    debug: true
    # rotate images?
    rotation: 0
    # output image size
    out_width: 1080
    out_height: 1920       
    # image source topic
    topic: "/background/color"
    # output port
    port: 7777
    print_fps: true
    FPS_STR: "webserver_fps"
    # Use sensor data Quality of Service for messages
    qos_sensor_data: false
    # Message queue size
    qos_history_depth: 20

    
